### ISSUE TITLE
Response code 600

### ISSUE THREAD

**Issue by dstephan1** [UCLA-CS130/Team22#49]
sometimes the status page logs 600, what is this?

**Comment by kevinazhu** [comment]
This is where it's coming from, when its an "other" response. So it's some type of response from the proxy that we don't handle probably.
![image](https://cloud.githubusercontent.com/assets/6497826/23792987/204260fc-053e-11e7-8e25-53da1383048a.png)

**Comment by dstephan1** [comment]
see fixes
